### PR TITLE
Added new language files generated with "extract-localization".

### PR DESCRIPTION
**Pull request by hendriks73**
* Added new language files generated with [extract-localization](https://github.com/hendriks73/extract-localization).
* Added a few items that weren't covered by the automatic extraction (`Find and Replace...`).
* `Bring <AppName> Window to Front` is missing in most of them. Does not seem to be too popular ;-)
* Added some missing strings to the existing language files.

### CODE REVIEW

**Comment by maremmle** [comment]
Hi @hendriks73,
sorry for the delay. 
On thing I have notice: The language files need to be named precisely as ``localize-mainmenu`` will use the exact same string given as ``target-language`` within the XLIFF from Xcode. 
So e.g. ``es_MX`` needs to be ``es-MX``.

**Comment by hendriks73** [comment]
Hey @maremmle,
I changed the file names to adhere to whatever `localize-mainmenu` uses.
Does that work for you?
(also change the corresponding java code that created the files)

**Comment by maremmle** [comment]
Thx @hendriks73 
I am not sure about the chines ones … I think uses soothing with 4 characters, like ``zh-Hans`` and all other sorts of different codes.

**Comment by hendriks73** [comment]
Yep.. the Chinese is tricky. IIRC cliff uses `zh-Hans`, but in existing apps it's always `zh_CN` — see for example `Chess.app`.

**Comment by maremmle** [comment]
Okay… I will see if issues will pop up

**Pull request merged**
